// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3qgW1j8QRd0P1ddexpSwH782DpFf8qfs',
    appId: '1:697964103328:web:4d9e2202eca4d3e1536bc5',
    messagingSenderId: '697964103328',
    projectId: 'iot-project-a67a9',
    authDomain: 'iot-project-a67a9.firebaseapp.com',
    databaseURL: 'https://iot-project-a67a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-a67a9.firebasestorage.app',
    measurementId: 'G-9EHZ2RPX9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjalegjXuRlhy7brILbRWJga30DU-_TL8',
    appId: '1:697964103328:android:82aca7688c91aaca536bc5',
    messagingSenderId: '697964103328',
    projectId: 'iot-project-a67a9',
    databaseURL: 'https://iot-project-a67a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-a67a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiW33PK5ioGBvfjHdo0EBLf14l7B-S65U',
    appId: '1:697964103328:ios:f7b89d7789f36ef4536bc5',
    messagingSenderId: '697964103328',
    projectId: 'iot-project-a67a9',
    databaseURL: 'https://iot-project-a67a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-a67a9.firebasestorage.app',
    iosBundleId: 'com.example.iotProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiW33PK5ioGBvfjHdo0EBLf14l7B-S65U',
    appId: '1:697964103328:ios:f7b89d7789f36ef4536bc5',
    messagingSenderId: '697964103328',
    projectId: 'iot-project-a67a9',
    databaseURL: 'https://iot-project-a67a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-a67a9.firebasestorage.app',
    iosBundleId: 'com.example.iotProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3qgW1j8QRd0P1ddexpSwH782DpFf8qfs',
    appId: '1:697964103328:web:046e3095bebf5210536bc5',
    messagingSenderId: '697964103328',
    projectId: 'iot-project-a67a9',
    authDomain: 'iot-project-a67a9.firebaseapp.com',
    databaseURL: 'https://iot-project-a67a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-a67a9.firebasestorage.app',
    measurementId: 'G-B1G24L8VRV',
  );

}